version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongodb
    environment:
      PORT: 3000
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongodb:27017/pokeminho
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
